services:
  apex-ords:
    build: .
    container_name: apex-ords
    restart: always
    ports:
      - "8383:8080"
    volumes:
      - ./ords_config:/opt/oracle/ords/config
      - ./wallet:/opt/oracle/wallet
    environment:
      - TZ=America/Asuncion
    networks:
      - default

networks:
  default:
    driver: bridge